version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      quarkus:
        patterns:
          - "io.quarkus*"
      maven-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/webapp"
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
